name: sv_museum
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  share_plus: ^7.2.1

flutter:
  uses-material-design: true
