name: sv_museum
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local DB
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2

  # Media
  image_picker: ^1.0.7
  file_picker: ^10.3.8
  audioplayers: ^6.5.1

  # Sharing
  share_plus: ^12.0.1

  # Text-to-Speech (Offline voice)
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # App Icon generator
  flutter_launcher_icons: ^0.13.1

  # Native Splash generator
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/splash/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F6F4EF"
  image: assets/splash/splash.png
  android: true
  ios: true
